server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:~/test                # url
    driver-class-name: org.h2.Driver   # H2 数据库驱动类的名称
    username: sa                       # H2 数据库用户名
    password: 123456                   # H2 数据库初始默认密码  (这里是一个提交验证的意思，而不是设置请注意)

  jpa:
    database: h2
    hibernate:
      ddl-auto: update                 # 数据库维护策略：更新（常用），即以a+的方式打开数据库（学过文件打开方式的应该懂）
    show-sql: true                     # 显示每一次jpa 操作实际对应的sql语句

  h2:
    console:
      path: /h2-console                # 控制台路径
      enabled: true                    # 启用控制台

  thymeleaf:
    cache: false                       # 不启用缓存
    servlet:
      content-type: text/html
    encoding: utf-8                    # view 模型编码 utf-8
    mode: HTML5                        # view 模型类型 html5
    suffix: .html                      # view 模型路径后缀
    prefix: classpath:/templates/      # view 模型路径前缀

  mvc:
    static-path-pattern: /static/**    # 静态资源路径模式

  resources:
    static-locations: classpath:/static/    # 静态资源位置



